#!/bin/sh
#
# Look up the given filename in the description file and output the
# text description
#
# FIXME
# - the description file is expected to be in the current dir

DESCRIPTIONS=descriptions.txt

FILE="$1"
if [ -z "$1" ]; then
    echo need filename
    exit 1
fi

LINE=$(egrep "^$FILE " "$DESCRIPTIONS")

if [ $? -ne 0 ]; then
    echo "Unknown file $FILE"
    exit 1
fi

echo "$LINE" | cut -d" " -f2-

